spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: wesamwesamwesam
  config:
    import: optional:file:.env[.properties] # This tells Spring to load the .env file
  jpa:
    show-sql: true
  jwt:
    secret-key: ${JWT_SECRET}
    access-token-validity-seconds: 900 #  7 days in seconds TODO: change to 900 `15 mins in seconds` for production
    refresh-token-validity-seconds: 604800 # 604800 is 7 days in seconds
