spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: wesamwesamwesam
  config:
    import: optional:file:.env[.properties] # This tells Spring to load the .env file and [.properties] to tell Spring to parse the file using the standard Key=Value property format
  jpa:
    show-sql: true
  jwt:
    secret-key: ${JWT_SECRET}
    access-token-validity-seconds: 30 # 900 is 15 min in seconds
    refresh-token-validity-seconds: 604800 # 604800 is 7 days in seconds
